/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IHeader: typeof import('./src/components/IHeader/IHeader.vue')['default']
    IMenu: typeof import('./src/components/IMenu/IMenu.vue')['default']
    LoginMain: typeof import("./src/components/LoginMain.vue")["default"]
    Menu: typeof import("./src/components/IMenu/IMenu.vue")["default"]
    NButton: typeof import('naive-ui')['NButton']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import("naive-ui")["NConfigProvider"]
    NDataTable: typeof import('naive-ui')['NDataTable']
    NForm: typeof import("naive-ui")["NForm"]
    NFormItem: typeof import("naive-ui")["NFormItem"]
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NRow: typeof import('naive-ui')['NRow']
    NSpace: typeof import("naive-ui")["NSpace"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
